# Page settings

baseurl = "http://schrismart.in/resume/"
languageCode = "en-us"
title = "Chris Martin Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-89270700-1"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Resume for Chris Martin, designed by Xiaoying Riley"
    author = "Chris Martin"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-2.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Chris Martin"
        tagline = "iOS Application Developer"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: schrismartin@me.com"
        title = "schrismartin@me.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+18657890002"
        title = "+18657890002"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//schrismart.in"
        title = "schrismart.in"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/schrismartin"
        title = "/in/schrismartin"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/schrismartin"
        title = "/schrismartin"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/ioschrismartin"
        title = "@ioschrismartin"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "BS in Computer Science"
        college = "University of Tennessee"
        dates = "2013 - 2017"

    # Languages section
    [params.languages]
        enable = true
        title = "Languages"

        [[params.languages.list]]
        language = "Swift"
        level = "3 Years"

        [[params.languages.list]]
        language = "C++"
        level = "4 Years"

        [[params.languages.list]]
        language = "C"
        level = "2 Years"

    # Interests section
    [params.interests]
        enable = false
        title = "Interests"

        [[params.interests.list]]
        interest = "Climbing"

        [[params.interests.list]]
        interest = "Snowboarding"

        [[params.interests.list]]
        interest = "Cooking"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "I am an iOS developer with a focus in designing/implementing smooth and intuitive user experiences. I'm always working on projects to enhance my programming practices, currently focusing on enhancing readability, effective code reuse, and design pattern conformance.\n\nI'm looking for a position where I can make meaningful contributions towards building creative solutions to common problems. I enjoy working on apps that are consumer facing, where the features I build directly impact user experience. Able to quickly relocate almost anywhere."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Software Development Intern"
        dates = "June 2016 – Present"
        company = "Oak Ridge National Laboratory"
        details = "Lead efforts in dependency reduction of [OpenStudio](https://www.openstudio.net), an open-source application used for whole-building energy modeling. Created converters between OpenStudio and Modellica programming language. Worked to develop internal web tool to perform audits on building energy consumption."

        [[params.jobs.list]]
        position = "Teaching Assistant"
        dates = "January 2016 – Present"
        company = "University of Tennessee, EECS Department "
        details = "Helped teach fundamentals of C++ programming to students new to the the field of computer science. Acted as an always-available reference personally and through email to procide C++ consultation, constructive criticism, and troubleshooting in compiler/IDE issues."

        [[params.jobs.list]]
        position = "Resident Assistant"
        dates = "February 2015 – December 2015"
        company = "University of Tennessee, Housing Department"
        details = "Maintained groups of 30-40 residents handling the home-to-university transition. Provided workshops focused on character building, academic success, time management, and social development. Strengthened skills in interpersonal communication, conflict resolution, and diplomatic policy enforcement."

        [[params.jobs.list]]
        position = "Operations Intern"
        dates = "June 2013 – May 2015"
        company = "Oak Ridge National Laboratory"
        details = "Began journey in computer programming by working to create visualizations tools to monitor and track operational data regarding ORNL's Titan Supercomputer. Worked with event-driven programming concepts to create interactive representations of realtime log data. Administered database used to collect and analyze processor faults and correlate data with external factors."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "I firmly believe that good programming is best learned by creating, reflecting, and revising. I enjoy taking on new challenges through personal projects to apply new skills and methods. Listed below are a few that I've been working on."

        [[params.projects.list]]
        title = "Syllabus"
        url = "http://www.syllabus-app.com"
        tagline = "iOS app used to visualize due dates, assignment weights, and track progress through a course."

        [[params.projects.list]]
        title = "The Narrator"
        url = "https://github.com/schrismartin/dont-shoot-the-messenger"
        tagline = "Procedurally generated text-based adventure played through Facebook's Messenger platform."

        [[params.projects.list]]
        title = "Jassem"
        url = "http://schrismart.in/jassem"
        tagline = "A web-based implementation of [Dr. Jim Plank](http://web.eecs.utk.edu/~plank/)'s assembly visualizer."

        [[params.projects.list]]
        title = "StudyLoop"
        url = "http://www.getstudyloop.com"
        tagline = "Slack-like group chat app for students to converse with classmates."

        [[params.projects.list]]
        title = "Available"
        url = "http://available.schrismart.in"
        tagline = "An app aimed to help groups of people find mutually available times to meet."

        [[params.projects.list]]
        title = "Music"
        url = "http://www.soundcloud.com/schrismartin"
        tagline = "I'll occasionally try my hand at remixing a song, several of which are posted here."

    # Skills section
    [params.skills]
        enable = false
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Swift"
        level = "90%"

        [[params.skills.list]]
        skill = "iOS Development"
        level = "80%"

        [[params.skills.list]]
        skill = "Git"
        level = "80%"

        [[params.skills.list]]
        skill = "C++"
        level = "80%"

        [[params.skills.list]]
        skill = "C"
        level = "75%"

        [[params.skills.list]]
        skill = "Javascript"
        level = "60%"

        [[params.skills.list]]
        skill = "Python"
        level = "45%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    #
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Chris Martin"
